// This file is automatically generated. Do not modify.

package gentest

import (
	"fmt"
)

var _ = fmt.Sprintf

type StSet struct {
	StringSet map[string]struct{} `thrift:"1,required" json:"stringSet"`
	I32Set    map[int32]struct{}  `thrift:"2,required" json:"i32Set"`
	BinarySet map[string]struct{} `thrift:"3,required" json:"binarySet"`
}
