// This file is automatically generated. Do not modify.

package gentest

import (
	"fmt"
)

var _ = fmt.Sprintf

type ByteAndListByte struct {
	AByte     int8   `thrift:"1,required" json:"aByte"`
	AListByte []int8 `thrift:"2,required" json:"aListByte"`
}
